CREATE DATABASE NurseryLinkDB;
GO
USE NurseryLinkDB;
GO
CREATE TABLE Nurseries (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(200) NOT NULL,
  Address NVARCHAR(500),
  Phone NVARCHAR(50)
);
GO
CREATE TABLE Parents (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  FullName NVARCHAR(200) NOT NULL,
  Email NVARCHAR(200),
  Phone NVARCHAR(50)
);
GO
CREATE TABLE Children (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  FullName NVARCHAR(200) NOT NULL,
  BirthDate DATE,
  NurseryId INT FOREIGN KEY REFERENCES Nurseries(Id),
  ParentId INT FOREIGN KEY REFERENCES Parents(Id)
);
GO
